### ISSUE TITLE
nullPointerException

### ISSUE THREAD

**Issue by mainframe2017** [AndreasRef/InstaClock#1]
Hello Team

I am beginner in coding please help me out 

I found error on running InstaClock.pde file with processing 

error: nullPointerException

line no: 103

**Comment by AndreasRef** [comment]
Hi
Did you change the `path` in line 24? The code in this repo loads it from my personal Dropbox (which only I have acces to), but you should load them from a location on your own device.

**Comment by mainframe2017** [comment]
There’s same issue occurred after change image path. How many Minimum images required for display clock? 
![unnamed](https://user-images.githubusercontent.com/25217920/78500775-188d9680-7776-11ea-8b32-c618ddf4acea.jpg)

**Comment by AndreasRef** [comment]
your data path folder needs to have the same structure as [this folder](https://github.com/AndreasRef/InstaClock/tree/master/instaClock_0_1/data) , not the data folder of "detectNewFilesInFolder" (which is just a work in progress sketch)

**Comment by mainframe2017** [comment]
same issues occur after following as per your guidelines

**Comment by AndreasRef** [comment]
I updated the data path in the code now, so it should work out of the box. Try running instaClock_0_1 with the updated code without changing anything, and see if that works?

**Comment by mainframe2017** [comment]
Thank you brother 
Its now loading all images and working fine but what was exact issue in previous code? also want to understand it mechanism how its work and how to add new images and what sequence of images I have to follow?

Also how it sync with real time clock?

**Comment by AndreasRef** [comment]
No problem, glad it works. It was a path issue with loading the images, the "path" needs to be a folder one level above the "data" folder. 

About the clock thing, it should sync with the seconds currently. If you want it to display hours and minutes you need to change those parts of the code. For reference see: [processing clock example](https://www.processing.org/examples/clock.html) + [minutes in processing reference](https://processing.org/reference/minute_.html)

Btw, this is just a hobby project done without pay, closing this issue now. gotta go back to work...
